name: Run Tests
on: push

jobs:
  container-job:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint and test
        run: yarn turbo run lint test
